#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width                2
bspc config window_gap                  8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# rules
bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Chromium desktop='^3'
bspc rule -a nemo state=floating

xsetroot -cursor_name left_ptr &

# autostart
xrdb merge .Xresources
picom -b
setxkbmap -option grp:alt_shift_toggle us,ru
feh --bg-fill --no-fehbg ~/walls/wall.jpg
$HOME/.config/polybar/launch.sh
dunst &
